// DEVICE TYPE
#define DRIVER_DEVICE 0x8000

// IOCTL CODES
// FUNCTION METHOD STARTS FROM 0X800
// < 0X800 RESVERED FOR MICROSOFT 
// SAME FOR DEVICE IDENTIFIERS NO < 0X8000
#define TEST_CODE CTL_CODE(DRIVER_DEVICE, 0x800, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

struct DataReceived
{
	PULONG DATA;
};